on: push
      
name: Reproducibility

jobs:
  render:
    name: Render assignment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest')"
      - name: Render mansucript
        run: |-
          Rscript -e "lapply(fs::dir_ls('assignment', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"
