
on: push  
name: Reproducible

jobs:
  render:
    name: Render Assignment
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1 
      - name: Install Package Dependencies
        run: |-
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Render mansucript
        run: |-
          Rscript -e "lapply(fs::dir_ls('assignment', glob='*.Rmd', recurse=TRUE), rmarkdown::render, envir = globalenv())"
          
